version: 0

dataset_class_debug: False
device: "cuda"
debug: True
data:
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA_CA/base_classes/train/coco/"
  val_batch_size: 1
  input_dimension: 300 # EfficientNetB2
  #   input_dimension: 384  ResNet18
heatmap:
  #output_dimension: 72 # EfficientNetB4 EfficientNetB1
  output_dimension: 80 # EfficientNetB2 EfficientNetB3
  # output_dimension: 96  ResNet18
  radius_scaling: 10
  fix_radius: True
  fix_radius_value: 5
max_objects_per_image: 1
model:
  encoder:
    encoder_name: EfficientNetB2Model #EfficientNetB2Model #EfficientNetB3Model #ResNet18Model #EfficientNetB3Model
    use_pretrained: True
    freeze_params: False
  decoder:
    #input_num_filter: 1792 # EfficientNetB0
    #input_num_filter: 1280 # EfficientNetB1
    input_num_filter: 1408 # EfficientNetB2
    #input_num_filter: 1536 # EfficientNetB3
    #input_num_filter: 1792 # EfficientNetB4
    #    input_num_filter: 512 ResNet18
    num_layers: 3
    output_num_filter: [ 768,512,128 ] # EfficientNetB2
    #    output_num_filter: [ 256,256,256 ] ResNet18
  heatmap_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,1 ]
    kernel_size: [ 3,1 ]
  offset_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  bbox_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  loss_weight:
    heatmap_head: 1
    bbox_head: 0.1
    offset_head: 0.1
    embedding_head: 1
logging:
  checkpoint_dir: "outputs/inference/EfficientNetB2Model"
evaluation:
  test_checkpoint_path: "/home/psrahul/MasterThesis/repo/Phase3/CLIPandDetect/outputs/training/EfficientNetB1Model/05092022_1134/epoch-800-loss-0.0738783"
  heatmap_pooling_kernel: 3
  topk_k: 1
  run_model_inference: True
