data:
  root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/train/coco/"
prediction_path: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/PASCAL_3_2_10/Unetresnet50/07102022_1433/bbox_predictions.npy"
prediction_path: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/PASCAL_3_2_10/Unetresnet50/08102022_1411/bbox_predictions.npy"
clip_embedding_path: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA_CA/support_images/base_classes/val/clip_embeddings.npy"
use_metric_data_path: False
metric_data_path: "/home/psrahul/MasterThesis/repo/Phase3/CLIPandDetect/outputs/metrics/EfficientNetB2Model/01092022_2057/data.npz"
perform_nms: True
post_processing:
  nms_iou_threshold: 0.5
  score_threshold: 0
  model_output_shape: 320
logging:
  root_dir: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/"
  checkpoint_dir: "PASCAL_3_2_10/metrics/"
