version: 0

train: False
test: True
dataset_class_debug: False
debug: False
test_debug: True
device: "cuda"
test_parameters:
  save_test_outputs: True
trainer:
  num_epochs: 2000
  resume_training: True
  checkpoint_path: "sftp://rsr@10.5.1.20:22/mnt/data/home/rsr/MasterThesis/repo/Phase6/Outputs/PASCAL_15_5_SA/Unetresnet50/09102022_1233/epoch-50-loss-1.1275787.pth"
  val_save_interval: 50
  bbox_heatmap_loss: False
  bbox_scatter_loss: True
  embedding_loss_start_epoch: -1
  bbox_loss_start_epoch: -1

data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_15_5_SA/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_15_5_SA/base_classes/val/coco/"
  test_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_15_5_SA/base_classes/train/coco/"
  train_aug: False
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 1
  input_dimension: 320 # EfficientNetB2
  num_workers: 32
  #   input_dimension: 384  ResNet18
heatmap:
  output_dimension: 320
  radius_scaling: 16
  fix_radius: True
  fix_radius_value: 5
max_objects_per_image: 1
smp:
  model: "Unet" #Unet" #"Unet" #DeepLabV3Plus"
  encoder_name: "resnet50" #"resnet50" #mobilenet_v2"
  encoder_weights: "imagenet" #"imagenet" #"swsl" #imagenet"
  decoder_output_classes: 16 #256 #16
  decoder_output_dimension: 320
  freeze_encoder: False

model:
  encoder:
    encoder_name: ResNet18Model #EfficientNetB2Model #EfficientNetB3Model #ResNet18Model #EfficientNetB3Model
    use_pretrained: True
    freeze_params: False
  decoder:
    #input_num_filter: 1792 # EfficientNetB0
    #input_num_filter: 1280 # EfficientNetB1
    #input_num_filter: 1408 # EfficientNetB2
    #input_num_filter: 1536 # EfficientNetB3
    #input_num_filter: 1792 # EfficientNetB4
    #input_num_filter: 2048 # ResNet50
    input_num_filter: 512 #ResNet18
    num_layers: 3
    output_num_filter: [ 512,128,1 ] # EfficientNetB2
    #    output_num_filter: [ 256,256,256 ] ResNet18
  heatmap_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,1 ]
    kernel_size: [ 3,1 ]
  offset_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  bbox_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  loss_weight:
    heatmap_head: 10
    bbox_head: 1
    offset_head: 0
    embedding_head: 1
logging:
  root_dir: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/"
  checkpoint_dir: "PASCAL_15_5_SA"
  display_log_fraction: 1
evaluation:
  heatmap_pooling_kernel: 3
  topk_k: 1