version: 0

train: False
test: True
dataset_class_debug: False
debug: False
test_debug: True
device: "cuda"
test_parameters:
  save_test_outputs: False

trainer:
  num_epochs: 1000
  resume_training: True
  checkpoint_path: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/PASCAL_3_2_10/Unetresnet50/07102022_1646/epoch-999-loss-5.0477887.pth"
  val_save_interval: 50
  bbox_heatmap_loss: False
  bbox_scatter_loss: True
  embedding_loss_start_epoch: 300
  bbox_loss_start_epoch: -1

data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/val/coco/"
  test_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/train/coco/"
  train_aug: True
  train_batch_size: 5
  val_batch_size: 5
  test_batch_size: 1
  input_dimension: 320 

heatmap:
  output_dimension: 320
  radius_scaling: 16
  fix_radius: True
  fix_radius_value: 1

smp:
  model: "Unet" #Unet" #"Unet" #DeepLabV3Plus"
  encoder_name: "resnet50" #"resnet50" #mobilenet_v2"
  encoder_weights: "imagenet" #"imagenet" #"swsl" #imagenet"
  decoder_output_classes: 3 #256 #16
  decoder_output_dimension: 320
  freeze_encoder: False

model:
  loss_weight:
    heatmap_head: 10
    bbox_head: 1
    offset_head: 0
    embedding_head: 1

logging:
  root_dir: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/"
  checkpoint_dir: "PASCAL_3_2_10"
  display_log_fraction: 1
evaluation:
  heatmap_pooling_kernel: 9
  topk_k: 5
  test_topk_k: 5