version: 0

train: True
test: True
dataset_class_debug: False
debug: True
device: "cuda"
test_parameters:
  save_test_outputs: True
data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA/base_classes/train/coco/"
  test_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA/base_classes/train/coco/"
  train_aug: False
  train_batch_size: 3
  val_batch_size: 3
  test_batch_size: 3
  input_dimension: 320 # EfficientNetB2
  #   input_dimension: 384  ResNet18
trainer:
  num_epochs: 300
  resume_training: False
  checkpoint_path: "/home/psrahul/MasterThesis/repo/Phase3/CLIPandDetect/outputs/training/Unetefficientnet-b2/10092022_1003/epoch-249-loss-0.1699464"
  val_save_interval: 100
  bbox_heatmap_loss: True
heatmap:
  output_dimension: 320
  radius_scaling: 4
  fix_radius: False
  fix_radius_value: 2
max_objects_per_image: 1
smp:
  model: "Unet" #"Unet" #DeepLabV3Plus"
  encoder_name: "resnet18" #"resnet50" #mobilenet_v2"
  encoder_weights: None #"imagenet" #"swsl" #imagenet"
  decoder_output_classes: 16 #256 #16
  decoder_output_dimension: 320
  freeze_encoder: False

model:
  encoder:
    encoder_name: ResNet50Model #EfficientNetB2Model #EfficientNetB3Model #ResNet18Model #EfficientNetB3Model
    use_pretrained: True
    freeze_params: False
  decoder:
    #input_num_filter: 1792 # EfficientNetB0
    #input_num_filter: 1280 # EfficientNetB1
    input_num_filter: 1408 # EfficientNetB2
    #input_num_filter: 1536 # EfficientNetB3
    #input_num_filter: 1792 # EfficientNetB4
    #    input_num_filter: 512 ResNet18
    num_layers: 3
    output_num_filter: [ 768,512,128 ] # EfficientNetB2
    #    output_num_filter: [ 256,256,256 ] ResNet18
  heatmap_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,1 ]
    kernel_size: [ 3,1 ]
  offset_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  bbox_head:
    input_num_filter: 128 # EfficientNetB2
    # input_num_filter: 256 ResNet18
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  loss_weight:
    heatmap_head: 1
    bbox_head: 0
    offset_head: 0
    embedding_head: 0
logging:
  checkpoint_dir: "outputs/training/"
  display_log_fraction: 1
evaluation:
  heatmap_pooling_kernel: 3
  topk_k: 1