version: 0
train: False
test: True

dataset_class_debug: False
debug: False
test_debug: False

device: "cuda"

test_parameters:
  save_test_outputs: True

trainer:
  num_epochs: 600
  resume_training: False
  train_checkpoint: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/PASCAL_3_2_10_SA/Training/DeepLabV3Plusefficientnet-b3/06102022_1001/epoch-300-loss-160.7034163.pth"
  test_checkpoint: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/PASCAL_3_2_10_SA/Training/DeepLabV3Plusefficientnet-b2/06102022_1157/epoch-500-loss-30.0053769.pth"

data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/val/coco/"
  test_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_3_2_10/base_classes/train/coco/"
  train_aug: False
  train_batch_size: 4 
  val_batch_size: 4 
  test_batch_size: 1
  input_dimension: 320 
 
heatmap:
  output_dimension: 320
  radius_scaling: 16
  fix_radius: True
  fix_radius_value: 5

smp:
  model: "DeepLabV3Plus" #Unet" #"Unet" #DeepLabV3Plus"
  encoder_name: "efficientnet-b2" #"resnet50" #"mobilenet_v2
  encoder_weights: "imagenet" #"imagenet" #"swsl" #imagenet"
  decoder_output_classes: 16 #256 #16
  decoder_output_dimension: 320
  freeze_encoder: False

loss:
  loss_weight:
    heatmap_head: 1
    bbox_head: 1
    embedding_head: 1
  center_scatter_loss: False
  center_heatmap_loss: True
  bbox_heatmap_loss: False
  bbox_scatter_loss: True
  embedding_loss_start_epoch: 300
  bbox_loss_start_epoch: -1

logging:
  root_dir: "/home/psrahul/MasterThesis/repo/Phase6/Outputs/"
  checkpoint_dir: "PASCAL_3_2_10_SA/Training"
  display_log_fraction: 1
  val_save_interval: 50

evaluation:
  heatmap_pooling_kernel: 3
  topk_k: 5
  test_topk_k: 5